// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	Issue struct {
		ID, ReviewFileID, IssueType, ReviewID, Title, Severity, Description, Content, File, Lines, Comment, ProcessedAt, CreatedAt, UserID, StatusID, LocalID, SuggestedFix string

		ReviewFile, Review, User string
	}
	ReviewFile struct {
		ID, ReviewID, ReviewType, Content, IssueStats, TrafficLight, CreatedAt, Summary, IsAccepted, StatusID string

		Review string
	}
	Review struct {
		ID, ProjectID, Title, Description, ExternalID, TrafficLight, CommitHash, SourceBranch, TargetBranch, Author, CreatedAt, DurationMS, ModelInfo, StatusID, PromptID, EffortMinutes, AiSlopScore, TriggeredByUserID, PRNumber string

		Project, Prompt, TriggeredByUser string
	}
	Project struct {
		ID, Title, VcsURL, Language, ProjectKey, PromptID, TaskTrackerID, SlackChannelID, CreatedAt, StatusID, Instructions, GithubOwner, GithubRepo, InstallationID string

		Prompt, TaskTracker, SlackChannel string
	}
	Prompt struct {
		ID, Title, Common, Architecture, Code, Security, Tests, Operability, CreatedAt, StatusID string
	}
	SlackChannel struct {
		ID, Title, Channel, WebhookURL, StatusID string
	}
	TaskTracker struct {
		ID, Title, AuthToken, FetchPrompt, CreatedAt, StatusID, URL string
	}
	ReviewJob struct {
		ID, ReviewID, Status, Attempts, LockedAt, LockedBy, LastError, CreatedAt, UpdatedAt string

		Review string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	Issue: struct {
		ID, ReviewFileID, IssueType, ReviewID, Title, Severity, Description, Content, File, Lines, Comment, ProcessedAt, CreatedAt, UserID, StatusID, LocalID, SuggestedFix string

		ReviewFile, Review, User string
	}{
		ID:           "issueId",
		ReviewFileID: "reviewFileId",
		IssueType:    "issueType",
		ReviewID:     "reviewId",
		Title:        "title",
		Severity:     "severity",
		Description:  "description",
		Content:      "content",
		File:         "file",
		Lines:        "lines",
		Comment:      "comment",
		ProcessedAt:  "processedAt",
		CreatedAt:    "createdAt",
		UserID:       "userId",
		StatusID:     "statusId",
		LocalID:      "localId",
		SuggestedFix: "suggestedFix",

		ReviewFile: "ReviewFile",
		Review:     "Review",
		User:       "User",
	},
	ReviewFile: struct {
		ID, ReviewID, ReviewType, Content, IssueStats, TrafficLight, CreatedAt, Summary, IsAccepted, StatusID string

		Review string
	}{
		ID:           "reviewFileId",
		ReviewID:     "reviewId",
		ReviewType:   "reviewType",
		Content:      "content",
		IssueStats:   "issueStats",
		TrafficLight: "trafficLight",
		CreatedAt:    "createdAt",
		Summary:      "summary",
		IsAccepted:   "isAccepted",
		StatusID:     "statusId",

		Review: "Review",
	},
	Review: struct {
		ID, ProjectID, Title, Description, ExternalID, TrafficLight, CommitHash, SourceBranch, TargetBranch, Author, CreatedAt, DurationMS, ModelInfo, StatusID, PromptID, EffortMinutes, AiSlopScore, TriggeredByUserID, PRNumber string

		Project, Prompt, TriggeredByUser string
	}{
		ID:                "reviewId",
		ProjectID:         "projectId",
		Title:             "title",
		Description:       "description",
		ExternalID:        "externalId",
		TrafficLight:      "trafficLight",
		CommitHash:        "commitHash",
		SourceBranch:      "sourceBranch",
		TargetBranch:      "targetBranch",
		Author:            "author",
		CreatedAt:         "createdAt",
		DurationMS:        "durationMS",
		ModelInfo:         "modelInfo",
		StatusID:          "statusId",
		PromptID:          "promptId",
		EffortMinutes:     "effortMinutes",
		AiSlopScore:       "aiSlopScore",
		TriggeredByUserID: "triggeredByUserId",
		PRNumber:          "prNumber",

		Project:         "Project",
		Prompt:          "Prompt",
		TriggeredByUser: "TriggeredByUser",
	},
	Project: struct {
		ID, Title, VcsURL, Language, ProjectKey, PromptID, TaskTrackerID, SlackChannelID, CreatedAt, StatusID, Instructions, GithubOwner, GithubRepo, InstallationID string

		Prompt, TaskTracker, SlackChannel string
	}{
		ID:             "projectId",
		Title:          "title",
		VcsURL:         "vcsURL",
		Language:       "language",
		ProjectKey:     "projectKey",
		PromptID:       "promptId",
		TaskTrackerID:  "taskTrackerId",
		SlackChannelID: "slackChannelId",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",
		Instructions:   "instructions",
		GithubOwner:    "githubOwner",
		GithubRepo:     "githubRepo",
		InstallationID: "installationId",

		Prompt:       "Prompt",
		TaskTracker:  "TaskTracker",
		SlackChannel: "SlackChannel",
	},
	Prompt: struct {
		ID, Title, Common, Architecture, Code, Security, Tests, Operability, CreatedAt, StatusID string
	}{
		ID:           "promptId",
		Title:        "title",
		Common:       "common",
		Architecture: "architecture",
		Code:         "code",
		Security:     "security",
		Tests:        "tests",
		Operability:  "operability",
		CreatedAt:    "createdAt",
		StatusID:     "statusId",
	},
	SlackChannel: struct {
		ID, Title, Channel, WebhookURL, StatusID string
	}{
		ID:         "slackChannelId",
		Title:      "title",
		Channel:    "channel",
		WebhookURL: "webhookURL",
		StatusID:   "statusId",
	},
	TaskTracker: struct {
		ID, Title, AuthToken, FetchPrompt, CreatedAt, StatusID, URL string
	}{
		ID:          "taskTrackerId",
		Title:       "title",
		AuthToken:   "authToken",
		FetchPrompt: "fetchPrompt",
		CreatedAt:   "createdAt",
		StatusID:    "statusId",
		URL:         "url",
	},
	ReviewJob: struct {
		ID, ReviewID, Status, Attempts, LockedAt, LockedBy, LastError, CreatedAt, UpdatedAt string

		Review string
	}{
		ID:        "reviewJobId",
		ReviewID:  "reviewId",
		Status:    "status",
		Attempts:  "attempts",
		LockedAt:  "lockedAt",
		LockedBy:  "lockedBy",
		LastError: "lastError",
		CreatedAt: "createdAt",
		UpdatedAt: "updatedAt",

		Review: "Review",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	Issue struct {
		Name, Alias string
	}
	ReviewFile struct {
		Name, Alias string
	}
	Review struct {
		Name, Alias string
	}
	Project struct {
		Name, Alias string
	}
	Prompt struct {
		Name, Alias string
	}
	SlackChannel struct {
		Name, Alias string
	}
	TaskTracker struct {
		Name, Alias string
	}
	ReviewJob struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Issue: struct {
		Name, Alias string
	}{
		Name:  "issues",
		Alias: "t",
	},
	ReviewFile: struct {
		Name, Alias string
	}{
		Name:  "reviewFiles",
		Alias: "t",
	},
	Review: struct {
		Name, Alias string
	}{
		Name:  "reviews",
		Alias: "t",
	},
	Project: struct {
		Name, Alias string
	}{
		Name:  "projects",
		Alias: "t",
	},
	Prompt: struct {
		Name, Alias string
	}{
		Name:  "prompts",
		Alias: "t",
	},
	SlackChannel: struct {
		Name, Alias string
	}{
		Name:  "slackChannels",
		Alias: "t",
	},
	TaskTracker: struct {
		Name, Alias string
	}{
		Name:  "taskTrackers",
		Alias: "t",
	},
	ReviewJob: struct {
		Name, Alias string
	}{
		Name:  "reviewJobs",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type Issue struct {
	tableName struct{} `pg:"issues,alias:t,discard_unknown_columns"`

	ID           int        `pg:"issueId,pk"`
	ReviewFileID int        `pg:"reviewFileId,use_zero"`
	IssueType    string     `pg:"issueType,use_zero"`
	ReviewID     int        `pg:"reviewId,use_zero"`
	Title        string     `pg:"title,use_zero"`
	Severity     string     `pg:"severity,use_zero"`
	Description  string     `pg:"description,use_zero"`
	Content      string     `pg:"content,use_zero"`
	File         string     `pg:"file,use_zero"`
	Lines        string     `pg:"lines,use_zero"`
	Comment      *string    `pg:"comment"`
	ProcessedAt  *time.Time `pg:"processedAt"`
	CreatedAt    time.Time  `pg:"createdAt,use_zero"`
	UserID       *int       `pg:"userId"`
	StatusID     int        `pg:"statusId,use_zero"`
	LocalID      *string    `pg:"localId"`
	SuggestedFix *string    `pg:"suggestedFix"`

	ReviewFile *ReviewFile `pg:"fk:reviewFileId,rel:has-one"`
	Review     *Review     `pg:"fk:reviewId,rel:has-one"`
	User       *User       `pg:"fk:userId,rel:has-one"`
}

type ReviewFile struct {
	tableName struct{} `pg:"reviewFiles,alias:t,discard_unknown_columns"`

	ID           int                  `pg:"reviewFileId,pk"`
	ReviewID     int                  `pg:"reviewId,use_zero"`
	ReviewType   string               `pg:"reviewType,use_zero"`
	Content      string               `pg:"content,use_zero"`
	IssueStats   ReviewFileIssueStats `pg:"issueStats,use_zero"`
	TrafficLight string               `pg:"trafficLight,use_zero"`
	CreatedAt    time.Time            `pg:"createdAt,use_zero"`
	Summary      string               `pg:"summary,use_zero"`
	IsAccepted   bool                 `pg:"isAccepted,use_zero"`
	StatusID     int                  `pg:"statusId,use_zero"`

	Review *Review `pg:"fk:reviewId,rel:has-one"`
}

type Review struct {
	tableName struct{} `pg:"reviews,alias:t,discard_unknown_columns"`

	ID                int             `pg:"reviewId,pk"`
	ProjectID         int             `pg:"projectId,use_zero"`
	Title             string          `pg:"title,use_zero"`
	Description       string          `pg:"description,use_zero"`
	ExternalID        string          `pg:"externalId,use_zero"`
	TrafficLight      string          `pg:"trafficLight,use_zero"`
	CommitHash        string          `pg:"commitHash,use_zero"`
	SourceBranch      string          `pg:"sourceBranch,use_zero"`
	TargetBranch      string          `pg:"targetBranch,use_zero"`
	Author            string          `pg:"author,use_zero"`
	CreatedAt         time.Time       `pg:"createdAt,use_zero"`
	DurationMS        int             `pg:"durationMS,use_zero"`
	ModelInfo         ReviewModelInfo `pg:"modelInfo,use_zero"`
	StatusID          int             `pg:"statusId,use_zero"`
	PromptID          int             `pg:"promptId,use_zero"`
	EffortMinutes     *int            `pg:"effortMinutes"`
	AiSlopScore       *float32        `pg:"aiSlopScore"`
	TriggeredByUserID *int            `pg:"triggeredByUserId"`
	PRNumber          *int            `pg:"prNumber"`

	Project         *Project `pg:"fk:projectId,rel:has-one"`
	Prompt          *Prompt  `pg:"fk:promptId,rel:has-one"`
	TriggeredByUser *User    `pg:"fk:triggeredByUserId,rel:has-one"`
}

type Project struct {
	tableName struct{} `pg:"projects,alias:t,discard_unknown_columns"`

	ID             int       `pg:"projectId,pk"`
	Title          string    `pg:"title,use_zero"`
	VcsURL         string    `pg:"vcsURL,use_zero"`
	Language       string    `pg:"language,use_zero"`
	ProjectKey     string    `pg:"projectKey,type:uuid,use_zero"`
	PromptID       int       `pg:"promptId,use_zero"`
	TaskTrackerID  *int      `pg:"taskTrackerId"`
	SlackChannelID *int      `pg:"slackChannelId"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`
	Instructions   *string   `pg:"instructions"`
	GithubOwner    *string   `pg:"githubOwner"`
	GithubRepo     *string   `pg:"githubRepo"`
	InstallationID *int64    `pg:"installationId"`

	Prompt       *Prompt       `pg:"fk:promptId,rel:has-one"`
	TaskTracker  *TaskTracker  `pg:"fk:taskTrackerId,rel:has-one"`
	SlackChannel *SlackChannel `pg:"fk:slackChannelId,rel:has-one"`
}

type Prompt struct {
	tableName struct{} `pg:"prompts,alias:t,discard_unknown_columns"`

	ID           int       `pg:"promptId,pk"`
	Title        string    `pg:"title,use_zero"`
	Common       string    `pg:"common,use_zero"`
	Architecture string    `pg:"architecture,use_zero"`
	Code         string    `pg:"code,use_zero"`
	Security     string    `pg:"security,use_zero"`
	Tests        string    `pg:"tests,use_zero"`
	Operability  string    `pg:"operability,use_zero"`
	CreatedAt    time.Time `pg:"createdAt,use_zero"`
	StatusID     int       `pg:"statusId,use_zero"`
}

type SlackChannel struct {
	tableName struct{} `pg:"slackChannels,alias:t,discard_unknown_columns"`

	ID         int    `pg:"slackChannelId,pk"`
	Title      string `pg:"title,use_zero"`
	Channel    string `pg:"channel,use_zero"`
	WebhookURL string `pg:"webhookURL,use_zero"`
	StatusID   int    `pg:"statusId,use_zero"`
}

type TaskTracker struct {
	tableName struct{} `pg:"taskTrackers,alias:t,discard_unknown_columns"`

	ID          int       `pg:"taskTrackerId,pk"`
	Title       string    `pg:"title,use_zero"`
	AuthToken   *string   `pg:"authToken"`
	FetchPrompt string    `pg:"fetchPrompt,use_zero"`
	CreatedAt   time.Time `pg:"createdAt,use_zero"`
	StatusID    int       `pg:"statusId,use_zero"`
	URL         string    `pg:"url,use_zero"`
}

type ReviewJob struct {
	tableName struct{} `pg:"reviewJobs,alias:t,discard_unknown_columns"`

	ID        int        `pg:"reviewJobId,pk"`
	ReviewID  int        `pg:"reviewId,use_zero"`
	Status    string     `pg:"status,use_zero"`
	Attempts  int        `pg:"attempts,use_zero"`
	LockedAt  *time.Time `pg:"lockedAt"`
	LockedBy  *string    `pg:"lockedBy"`
	LastError *string    `pg:"lastError"`
	CreatedAt time.Time  `pg:"createdAt,use_zero"`
	UpdatedAt time.Time  `pg:"updatedAt,use_zero"`

	Review *Review `pg:"fk:reviewId,rel:has-one"`
}
