-- v0.2: GitHub service migration

-- Projects: GitHub coordinates
ALTER TABLE "projects" ADD COLUMN "githubOwner" text;
ALTER TABLE "projects" ADD COLUMN "githubRepo" text;
ALTER TABLE "projects" ADD COLUMN "installationId" bigint;

-- Reviews: who triggered, which PR
ALTER TABLE "reviews" ADD COLUMN "triggeredByUserId" integer;
ALTER TABLE "reviews" ADD COLUMN "prNumber" integer;
ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_users_triggered"
    FOREIGN KEY ("triggeredByUserId") REFERENCES "users"("userId")
    ON DELETE SET NULL ON UPDATE RESTRICT NOT DEFERRABLE;

-- Job queue
CREATE TABLE "reviewJobs" (
    "reviewJobId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "reviewId"    integer NOT NULL,
    "status"      text    NOT NULL DEFAULT 'pending',
    "attempts"    integer NOT NULL DEFAULT 0,
    "lockedAt"    timestamp with time zone,
    "lockedBy"    text,
    "lastError"   text,
    "createdAt"   timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt"   timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "reviewJobs_pkey" PRIMARY KEY ("reviewJobId"),
    CONSTRAINT "Ref_reviewJobs_to_reviews" FOREIGN KEY ("reviewId")
        REFERENCES "reviews"("reviewId")
        ON DELETE CASCADE ON UPDATE RESTRICT NOT DEFERRABLE,
    CONSTRAINT "reviewJobs_status_check" CHECK ("status" IN ('pending','running','done','failed'))
);

CREATE INDEX "ix_reviewJobs_status_createdAt" ON "reviewJobs" ("status", "createdAt")
    WHERE "status" = 'pending';
CREATE INDEX "ix_reviewJobs_reviewId" ON "reviewJobs" ("reviewId");
