-- v0.2: Per-PR Claude session cache
CREATE TABLE "prSessions" (
    "prSessionId"     integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "projectId"       integer     NOT NULL,
    "prNumber"        integer     NOT NULL,
    "claudeSessionId" text        NOT NULL,
    "createdAt"       timestamptz NOT NULL DEFAULT now(),
    "updatedAt"       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "prSessions_pkey" PRIMARY KEY ("prSessionId"),
    CONSTRAINT "Ref_prSessions_to_projects" FOREIGN KEY ("projectId")
        REFERENCES "projects"("projectId")
        ON DELETE CASCADE ON UPDATE RESTRICT NOT DEFERRABLE
);

CREATE UNIQUE INDEX "uq_prSessions_project_pr"
    ON "prSessions" ("projectId", "prNumber");
