CREATE TABLE "prompts" (
	"promptId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"common" text NOT NULL,
	"architecture" text NOT NULL,
	"code" text NOT NULL,
	"security" text NOT NULL,
	"tests" text NOT NULL,
	"operability" text NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "prompts_pkey" PRIMARY KEY("promptId")
);

CREATE TABLE "statuses" (
	"statusId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"alias" varchar(64),
	CONSTRAINT "statuses_pkey" PRIMARY KEY("statusId")
);

CREATE TABLE "taskTrackers" (
	"taskTrackerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"url" varchar(255) NOT NULL,
	"authToken" varchar(255),
	"fetchPrompt" text NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "taskTrackers_pkey" PRIMARY KEY("taskTrackerId")
);

CREATE TABLE "slackChannels" (
	"slackChannelId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"channel" varchar(255) NOT NULL,
	"webhookURL" varchar(1024) NOT NULL,
	"statusId" integer NOT NULL,
	CONSTRAINT "slackChannels_pkey" PRIMARY KEY("slackChannelId")
);

CREATE TABLE "projects" (
	"projectId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"vcsURL" varchar(255) NOT NULL,
	"language" varchar(32) NOT NULL,
	"projectKey" uuid NOT NULL,
	"instructions" text,
	"promptId" integer NOT NULL,
	"taskTrackerId" integer,
	"slackChannelId" integer,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	"githubOwner" text,
	"githubRepo" text,
	"installationId" bigint,
	CONSTRAINT "projects_pkey" PRIMARY KEY("projectId"),
	CONSTRAINT "UNQ_projects_projectKey" UNIQUE("projectKey")
);

CREATE TABLE "reviews" (
	"reviewId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"projectId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" varchar(2048) NOT NULL,
	"externalId" varchar(32) NOT NULL,
	"trafficLight" varchar(32) NOT NULL DEFAULT 'none',
	"commitHash" varchar(40) NOT NULL,
	"sourceBranch" varchar(255) NOT NULL,
	"targetBranch" varchar(255) NOT NULL,
	"author" varchar(255) NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"durationMS" integer NOT NULL DEFAULT 0,
	"modelInfo" jsonb NOT NULL DEFAULT '{}',
	"statusId" integer NOT NULL,
	"promptId" integer NOT NULL,
	"effortMinutes" integer,
	"aiSlopScore" real,
	"triggeredByUserId" integer,
	"prNumber" integer,
	CONSTRAINT "reviews_pkey" PRIMARY KEY("reviewId")
);

CREATE TABLE "reviewFiles" (
	"reviewFileId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"reviewId" integer NOT NULL,
	"reviewType" varchar(64) NOT NULL,
	"content" text NOT NULL,
	"issueStats" jsonb NOT NULL DEFAULT '{}',
	"trafficLight" varchar(32) NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"summary" varchar(2048) NOT NULL,
	"isAccepted" boolean NOT NULL DEFAULT false,
	"statusId" integer NOT NULL,
	CONSTRAINT "reviewFiles_pkey" PRIMARY KEY("reviewFileId")
);

CREATE TABLE "reviewJobs" (
	"reviewJobId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"reviewId"    integer NOT NULL,
	"status"      text    NOT NULL DEFAULT 'pending',
	"attempts"    integer NOT NULL DEFAULT 0,
	"lockedAt"    timestamptz,
	"lockedBy"    text,
	"lastError"   text,
	"createdAt"   timestamptz NOT NULL DEFAULT now(),
	"updatedAt"   timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "reviewJobs_pkey" PRIMARY KEY ("reviewJobId")
);

ALTER TABLE "reviewJobs" ADD CONSTRAINT "reviewJobs_status_check" CHECK ("status" IN ('pending','running','done','failed'));

CREATE TABLE "issues" (
	"issueId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"reviewFileId" integer NOT NULL,
	"issueType" varchar(32) NOT NULL,
	"reviewId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"severity" varchar(16) NOT NULL,
	"description" text NOT NULL,
	"content" text NOT NULL,
	"file" varchar(255) NOT NULL,
	"lines" varchar(255) NOT NULL,
	"comment" varchar(255),
	"localId" varchar(16),
	"processedAt" timestamptz,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"userId" integer,
	"suggestedFix" text,
	"statusId" integer NOT NULL,
	CONSTRAINT "issues_pkey" PRIMARY KEY("issueId")
);

CREATE TABLE "users" (
	"userId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login" varchar(64) NOT NULL,
	"password" varchar(64) NOT NULL,
	"authKey" varchar(32),
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"lastActivityAt" timestamptz,
	"statusId" integer NOT NULL,
	CONSTRAINT "users_pkey" PRIMARY KEY("userId")
);

CREATE INDEX "IX_reviews_projectId" ON "reviews" (
	"projectId"
);

CREATE INDEX "IX_reviews_externalId" ON "reviews" (
	"externalId"
);

CREATE INDEX "IX_reviews_reviewId" ON "reviewFiles" (
	"reviewId"
);

CREATE INDEX "IX_issues_statusId" ON "issues" (
	"statusId"
);

CREATE INDEX "IX_issues_reviewId" ON "issues" (
	"reviewId"
);

CREATE INDEX "IX_issues_reviewFileId" ON "issues" (
	"reviewFileId"
);

CREATE INDEX "ix_issues_userId" ON "issues" (
	"userId"
);

CREATE INDEX "ix_projects_statusId" ON "projects" (
	"statusId"
);

CREATE INDEX "ix_prompts_statusId" ON "prompts" (
	"statusId"
);

CREATE INDEX "ix_reviewFiles_statusId" ON "reviewFiles" (
	"statusId"
);

CREATE INDEX "ix_reviews_promptId" ON "reviews" (
	"promptId"
);

CREATE INDEX "ix_slackChannels_statusId" ON "slackChannels" (
	"statusId"
);

CREATE INDEX "ix_taskTrackers_statusId" ON "taskTrackers" (
	"statusId"
);

CREATE INDEX "ix_users_statusId" ON "users" (
	"statusId"
);

CREATE INDEX "ix_projects_slackChannelId" ON "projects" (
	"slackChannelId"
);

CREATE INDEX "ix_reviews_statusId" ON "reviews" (
	"statusId"
);

CREATE INDEX "ix_projects_taskTrackerId" ON "projects" (
	"taskTrackerId"
);

CREATE INDEX "ix_projects_promptId" ON "projects" (
	"promptId"
);

CREATE INDEX "ix_reviewJobs_status_createdAt" ON "reviewJobs" ("status", "createdAt")
	WHERE "status" = 'pending';

CREATE INDEX "ix_reviewJobs_reviewId" ON "reviewJobs" ("reviewId");

ALTER TABLE "prompts" ADD CONSTRAINT "Ref_prompts_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "taskTrackers" ADD CONSTRAINT "Ref_taskTrackers_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "slackChannels" ADD CONSTRAINT "Ref_slackChannels_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_prompts" FOREIGN KEY ("promptId")
	REFERENCES "prompts"("promptId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_taskTrackers" FOREIGN KEY ("taskTrackerId")
	REFERENCES "taskTrackers"("taskTrackerId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_slackChannels" FOREIGN KEY ("slackChannelId")
	REFERENCES "slackChannels"("slackChannelId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_projects" FOREIGN KEY ("projectId")
	REFERENCES "projects"("projectId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_prompts" FOREIGN KEY ("promptId")
	REFERENCES "prompts"("promptId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_users_triggered" FOREIGN KEY ("triggeredByUserId")
	REFERENCES "users"("userId")
	ON DELETE SET NULL
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviewFiles" ADD CONSTRAINT "Ref_reviewFiles_to_reviews" FOREIGN KEY ("reviewId")
	REFERENCES "reviews"("reviewId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviewFiles" ADD CONSTRAINT "Ref_reviewFiles_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviewJobs" ADD CONSTRAINT "Ref_reviewJobs_to_reviews" FOREIGN KEY ("reviewId")
	REFERENCES "reviews"("reviewId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_reviewFiles" FOREIGN KEY ("reviewFileId")
	REFERENCES "reviewFiles"("reviewFileId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_users" FOREIGN KEY ("userId")
	REFERENCES "users"("userId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_reviews" FOREIGN KEY ("reviewId")
	REFERENCES "reviews"("reviewId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "users" ADD CONSTRAINT "Ref_users_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

